kw_list:
  "PCR": {
    "PointCloud": [
        ["PointCloud"], ["Point Cloud"], 
    ], 
    "PCR": [
        ["Registration"], 
        ["3D", "Descriptor"], 
        ["3D", "Detector"], 
        ["3D", "Detection"], 
        ["Local", "Feature"], 
        ["Match", "Matching"]
    ], 
    "PCR and Transformer": [
        ["Registration", "Transformer"],
    ]
  }
  "Transformer": {
    "Transfomer": [
      ["Transformer"]
    ]
  }
  "NeRF": {
   "NeRF": [
    ["NeRF"]
   ]
  }
# save path
arxiv_data_dir: "./data_all"
map_data_dir: "D:/DData/7.Papers/ArxivEveryDayPaper"